# Generated by Django 5.2.12 on 2026-03-24 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_consultationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationrequest',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patienteducation',
            name='topic',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='patienteducation',
            name='url',
            field=models.URLField(),
        ),
    ]
