# Generated by Django 5.2.12 on 2026-03-24 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_consultationrequest_accepted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationrequest',
            name='joined',
            field=models.BooleanField(default=False),
        ),
    ]
