# Generated by Django 5.2.12 on 2026-04-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0009_consultationrequest_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationrequest',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
