# Generated by Django 5.2.4 on 2026-04-30 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0011_doctorprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
