# Generated by Django 5.2.12 on 2026-05-25 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0012_doctorprofile_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=15),
        ),
        migrations.CreateModel(
            name='DoctorReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_overall', models.IntegerField(default=5)),
                ('rating_listening', models.IntegerField(default=5)),
                ('rating_guidance', models.IntegerField(default=5)),
                ('rating_clarity', models.IntegerField(default=5)),
                ('rating_recommend', models.IntegerField(default=5)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='doctor.consultationrequest')),
            ],
        ),
    ]
